CREATE TABLE IF NOT EXISTS sport_courts (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    address VARCHAR(255) NOT NULL,
    city VARCHAR(255) NOT NULL,
    state VARCHAR(255) NOT NULL,
    zip_code VARCHAR(20) NOT NULL,
    cnpj VARCHAR(20),
    neighborhood VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    type VARCHAR(50) NOT NULL,
    status VARCHAR(50),
    image_url TEXT,
    phone VARCHAR(20) NOT NULL,
    email VARCHAR(255),
    website VARCHAR(255),
    opening_hours VARCHAR(255),
    price DECIMAL(10, 2),
    amenities TEXT,
    location VARCHAR(255),
    owner_id BIGINT NOT NULL,
    rules TEXT,
    payment_methods TEXT,
    reviews TEXT,
    ratings DECIMAL(3, 2),
    created_at TIMESTAMP DEFAULT now(),
    FOREIGN KEY (owner_id) REFERENCES owners(id) ON DELETE CASCADE
);