CREATE TABLE IF NOT EXISTS schedules(
id BIGSERIAL PRIMARY KEY,
status VARCHAR(255) NOT NULL,
date TIMESTAMP NOT NULL,
time TIME NOT NULL,
duration INT NOT NULL,
price DECIMAL(10,2) NOT NULL,
qtd_athletes INTEGER NOT NULL DEFAULT 0,
sport_court_id BIGINT NOT NULL,
athlete_id BIGINT NOT NULL,
FOREIGN KEY (sport_court_id) REFERENCES sport_courts(id) ON DELETE CASCADE,
FOREIGN KEY (athlete_id) REFERENCES athletes(id) ON DELETE CASCADE,
created_at TIMESTAMP DEFAULT now(),
updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);